export const FONT_OPTIONS = [
  { val: 'sans-serif', label: 'Sans' },
  { val: 'serif', label: 'Serif' },
  { val: 'monospace', label: 'Mono' },
  { val: 'cursive', label: 'Cursive' },
  { val: 'system-ui', label: 'System UI' },
  { val: 'Arial', label: 'Arial' },
  { val: 'Helvetica', label: 'Helvetica' },
  { val: '"Times New Roman"', label: 'Times New Roman' },
  { val: 'Georgia', label: 'Georgia' },
  { val: 'Verdana', label: 'Verdana' },
  { val: 'Tahoma', label: 'Tahoma' },
  { val: '"Trebuchet MS"', label: 'Trebuchet MS' },
  { val: 'Impact', label: 'Impact' },
  { val: '"Comic Sans MS"', label: 'Comic Sans MS' },
  { val: '"Courier New"', label: 'Courier New' },
  { val: '"Microsoft YaHei", "微软雅黑"', label: 'YaHei (微软雅黑)' },
  { val: '"SimSun", "宋体"', label: 'SimSun (宋体)' },
  { val: '"SimHei", "黑体"', label: 'SimHei (黑体)' },
  { val: '"KaiTi", "楷体"', label: 'KaiTi (楷体)' },
  { val: '"FangSong", "仿宋"', label: 'FangSong (仿宋)' },
  { val: '"PingFang SC"', label: 'PingFang SC' },
  { val: '"Hiragino Sans GB"', label: 'Hiragino Sans GB' },
  { val: '"Source Han Sans SC"', label: 'Source Han Sans (思源黑体)' },
  { val: '"Source Han Serif SC"', label: 'Source Han Serif (思源宋体)' },
];
